### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by tegk** [querycap/istio-envoy-arm64#1]
Could I ask you kindly to provide detailed documentation how to compile Istio on ARM64?

medium post with a tutorial or something :-) ?

**Comment by morlay** [comment]
two parts 

## build istio-enovy 
### deps
https://github.com/querycap/istio-envoy-arm64/blob/master/build-env/Dockerfile

### build
https://github.com/querycap/istio-envoy-arm64/blob/master/istio-envoy/Dockerfile#L19

important here to use local java for using arm64 version of hsdis

## build istio go 
https://github.com/querycap/istio

all steps in Dockerfiles
