### ISSUE TITLE
miss error when build in arm linux

### ISSUE THREAD

**Issue by huanghuangzym** [querycap/istio-envoy-arm64#6]
Loading: 0 packages loaded
    currently loading: src/envoy
Analyzing: target //src/envoy:envoy (1 packages loaded, 0 targets configured)
WARNING: /root/.cache/bazel/_bazel_root/596b0cd1ad0211ef049437fdd23e86ea/external/remote_java_tools_linux/BUILD:671:1: in hdrs attribute of cc_library rule @remote_java_tools_linux//:combiners: Artifact 'external/remote_java_tools_linux/java_tools/src/tools/singlejar/zip_headers.h' is duplicated (through '@remote_java_tools_linux//:transient_bytes' and '@remote_java_tools_linux//:zip_headers'). Since this rule was created by the macro 'cc_library', the error might have been caused by the macro implementation
Analyzing: target //src/envoy:envoy (640 packages loaded, 29868 targets configured)
Analyzing: target //src/envoy:envoy (648 packages loaded, 32815 targets configured)
INFO: Analyzed target //src/envoy:envoy (649 packages loaded, 36029 targets configured).
INFO: Found 1 target...
[0 / 3] [Prepa] BazelWorkspaceStatusAction stable-status.txt
INFO: From Executing genrule @com_lightstep_tracer_cpp//:generate_version_h:
CMake Warning at CMakeLists.txt:74 (message):
  WITH_GRPC is not set; building without dynamic loading support.

-- The C compiler identification is Clang 9.0.0
-- The CXX compiler identification is Clang 9.0.0
-- Check for working C compiler: /usr/lib/llvm-9/bin/clang
-- Check for working C compiler: /usr/lib/llvm-9/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/lib/llvm-9/bin/clang++
-- Check for working CXX compiler: /usr/lib/llvm-9/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/tmp.GqM18YeMYn
-- Cache values
BUILD_SHARED_LIBS:BOOL=ON
BUILD_STATIC_LIBS:BOOL=ON
CMAKE_BUILD_TYPE:STRING=
CMAKE_INSTALL_PREFIX:PATH=/usr/local
DEFAULT_SSL_ROOTS_PEM:STRING=
HEADERS_ONLY:BOOL=ON
WITH_CARES:BOOL=OFF
WITH_DYNAMIC_LOAD:BOOL=ON
WITH_GRPC:BOOL=OFF
WITH_LIBEVENT:BOOL=OFF
INFO: From Executing genrule @io_opentracing_cpp//:generate_version_h:
-- The C compiler identification is Clang 9.0.0
-- The CXX compiler identification is Clang 9.0.0
-- Check for working C compiler: /usr/lib/llvm-9/bin/clang
-- Check for working C compiler: /usr/lib/llvm-9/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/lib/llvm-9/bin/clang++
-- Check for working CXX compiler: /usr/lib/llvm-9/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- clang-tidy found: /usr/lib/llvm-9/bin/clang-tidy
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/tmp.c5KWwgNpkf
-- Cache values
BUILD_DYNAMIC_LOADING:BOOL=ON
BUILD_MOCKTRACER:BOOL=OFF
BUILD_SHARED_LIBS:BOOL=ON
BUILD_STATIC_LIBS:BOOL=ON
BUILD_TESTING:BOOL=OFF
CLANG_TIDY_EXE:FILEPATH=/usr/lib/llvm-9/bin/clang-tidy
CMAKE_BUILD_TYPE:STRING=
CMAKE_INSTALL_PREFIX:PATH=/usr/local
ENABLE_LINTING:BOOL=ON
INFO: From CcCmakeMakeRule external/envoy/bazel/foreign_cc/zlib/include [for host]:
rules_foreign_cc: Cleaning temp directories
INFO: From CcCmakeMakeRule external/envoy/bazel/foreign_cc/zlib/include:
[1,219 / 4,559] Compiling external/com_google_protobuf/src/google/protobuf/api.pb.cc [for host]; 1s processwrapper-sandbox ... (8 actions, 7 running)
[1,476 / 4,560] CcCmakeMakeRule external/envoy/bazel/foreign_cc/nghttp2/include; 20s processwrapper-sandbox ... (8 actions, 7 running)
rules_foreign_cc: Cleaning temp directories
INFO: From CcCmakeMakeRule external/envoy/bazel/foreign_cc/nghttp2/include:
rules_foreign_cc: Cleaning temp directories
INFO: From Compiling external/antlr4_runtimes/runtime/Cpp/runtime/src/atn/ParserATNSimulator.cpp:
external/antlr4_runtimes/runtime/Cpp/runtime/src/atn/ParserATNSimulator.cpp:56:42: warning: field 'parser' will be initialized after field 'decisionToDFA' [-Wreorder]
: ATNSimulator(atn, sharedContextCache), parser(parser), decisionToDFA(decisionToDFA) {
                                         ^
1 warning generated.
INFO: From Compiling external/antlr4_runtimes/runtime/Cpp/runtime/src/Vocabulary.cpp:
In file included from external/antlr4_runtimes/runtime/Cpp/runtime/src/Vocabulary.cpp:8:
external/antlr4_runtimes/runtime/Cpp/runtime/src/Vocabulary.h:19:17: warning: explicitly defaulted copy assignment operator is implicitly deleted [-Wdefaulted-function-deleted]
    Vocabulary& operator=(Vocabulary const&) = default;
                ^
external/antlr4_runtimes/runtime/Cpp/runtime/src/Vocabulary.h:187:36: note: copy assignment operator of 'Vocabulary' is implicitly deleted because field '_literalNames' has no copy assignment operator
    std::vector<std::string> const _literalNames;
                                   ^
1 warning generated.
INFO: From Compiling external/antlr4_runtimes/runtime/Cpp/runtime/src/LexerInterpreter.cpp:
In file included from external/antlr4_runtimes/runtime/Cpp/runtime/src/LexerInterpreter.cpp:11:
external/antlr4_runtimes/runtime/Cpp/runtime/src/Vocabulary.h:19:17: warning: explicitly defaulted copy assignment operator is implicitly deleted [-Wdefaulted-function-deleted]
    Vocabulary& operator=(Vocabulary const&) = default;
                ^
external/antlr4_runtimes/runtime/Cpp/runtime/src/Vocabulary.h:187:36: note: copy assignment operator of 'Vocabulary' is implicitly deleted because field '_literalNames' has no copy assignment operator
    std::vector<std::string> const _literalNames;
                                   ^
1 warning generated.
INFO: From Compiling external/antlr4_runtimes/runtime/Cpp/runtime/src/DiagnosticErrorListener.cpp:
In file included from external/antlr4_runtimes/runtime/Cpp/runtime/src/DiagnosticErrorListener.cpp:7:
external/antlr4_runtimes/runtime/Cpp/runtime/src/atn/ATNConfig.h:90:16: warning: explicitly defaulted copy assignment operator is implicitly deleted [-Wdefaulted-function-deleted]
    ATNConfig& operator=(ATNConfig const&) = default;
               ^
external/antlr4_runtimes/runtime/Cpp/runtime/src/atn/ATNConfig.h:41:18: note: copy assignment operator of 'ATNConfig' is implicitly deleted because field 'alt' is of const-qualified type 'const size_t' (aka 'const unsigned long')
    const size_t alt;
                 ^
1 warning generated.
INFO: From Compiling external/antlr4_runtimes/runtime/Cpp/runtime/src/Parser.cpp:
In file included from external/antlr4_runtimes/runtime/Cpp/runtime/src/Parser.cpp:22:
external/antlr4_runtimes/runtime/Cpp/runtime/src/tree/pattern/ParseTreePattern.h:33:23: warning: explicitly defaulted copy assignment operator is implicitly deleted [-Wdefaulted-function-deleted]
    ParseTreePattern& operator=(ParseTreePattern const&) = default;
                      ^
external/antlr4_runtimes/runtime/Cpp/runtime/src/tree/pattern/ParseTreePattern.h:92:15: note: copy assignment operator of 'ParseTreePattern' is implicitly deleted because field 'patternRuleIndex' is of const-qualified type 'const int'
    const int patternRuleIndex;
              ^
1 warning generated.
INFO: From Compiling external/antlr4_runtimes/runtime/Cpp/runtime/src/DefaultErrorStrategy.cpp:
In file included from external/antlr4_runtimes/runtime/Cpp/runtime/src/DefaultErrorStrategy.cpp:17:
external/antlr4_runtimes/runtime/Cpp/runtime/src/Vocabulary.h:19:17: warning: explicitly defaulted copy assignment operator is implicitly deleted [-Wdefaulted-function-deleted]
    Vocabulary& operator=(Vocabulary const&) = default;
                ^
external/antlr4_runtimes/runtime/Cpp/runtime/src/Vocabulary.h:187:36: note: copy assignment operator of 'Vocabulary' is implicitly deleted because field '_literalNames' has no copy assignment operator
    std::vector<std::string> const _literalNames;
                                   ^
1 warning generated.
ERROR: /root/.cache/bazel/_bazel_root/596b0cd1ad0211ef049437fdd23e86ea/external/com_googlesource_chromium_v8/BUILD.bazel:21:1: Executing genrule @com_googlesource_chromium_v8//:build failed (Exit 1) process-wrapper failed: error executing command
  (cd /root/.cache/bazel/_bazel_root/596b0cd1ad0211ef049437fdd23e86ea/sandbox/processwrapper-sandbox/624/execroot/io_istio_proxy && \
  exec env - \
    BAZEL_COMPILER=clang \
    BAZEL_CXXOPTS='-stdlib=libc++' \
    BAZEL_LINKLIBS=-l%:libc++.a:-l%:libc++abi.a:-lm \
    BAZEL_LINKOPTS=-lm \
    CC=clang \
    CXX=clang++ \
    CXXFLAGS='-stdlib=libc++' \
    LDFLAGS='-stdlib=libc++' \
PATH=/usr/lib/llvm-9/bin:/usr/lib/llvm-9/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    TMPDIR=/tmp \
/root/.cache/bazel/_bazel_root/install/f40bcc048855e8aaa3d5878d1079cbde/process-wrapper '--timeout=0' '--kill_delay=15' /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; #!/bin/bash

set -e

# This works only on Linux-{x86_64,s390x,aarch64} and macOS-x86_64.
case "$(uname -s)-$(uname -m)" in
Linux-x86_64|Linux-s390x|Linux-aarch64|Darwin-x86_64)
  ;;
*)
  echo "ERROR: wee8 is currently supported only on Linux-{x86_64,s390x,aarch64} and macOS-x86_64." >&2
  exit 1
esac

# Bazel magic.
ROOT=$(dirname external/com_googlesource_chromium_v8/wee8/BUILD.gn)/..
pushd $ROOT/wee8

# Clean after previous build.
rm -rf out/wee8

# Export compiler configuration.
if [[ ( `uname` == "Darwin" && ${CXX-} == "" ) || ${CXX-} == *"clang"* ]]; then
  export IS_CLANG=true
  export CC=${CC:-clang}
  export CXX=${CXX:-clang++}
else
  export IS_CLANG=false
  export CC=${CC:-gcc}
  export CXX=${CXX:-g++}
fi

export AR=${AR:-ar}
export NM=${NM:-nm}

# Hook sanitizers.
if [[ ${ENVOY_ASAN-} == "1" ]]; then
  WEE8_BUILD_ARGS+=" is_asan=true"
  WEE8_BUILD_ARGS+=" is_lsan=true"
fi
if [[ ${ENVOY_UBSAN_VPTR-} == "1" ]]; then
  WEE8_BUILD_ARGS+=" is_ubsan=true"
  WEE8_BUILD_ARGS+=" is_ubsan_vptr=true"
fi
if [[ ${ENVOY_MSAN-} == "1" ]]; then
  WEE8_BUILD_ARGS+=" is_msan=true"
  export LDFLAGS="${LDFLAGS} -L/opt/libcxx_msan/lib -Wl,-rpath,/opt/libcxx_msan/lib"
fi
if [[ ${ENVOY_TSAN-} == "1" ]]; then
  WEE8_BUILD_ARGS+=" is_tsan=true"
fi

# Release build.
WEE8_BUILD_ARGS+=" is_debug=false"
# Clang or not Clang, that is the question.
WEE8_BUILD_ARGS+=" is_clang=$IS_CLANG"
# Hack to disable bleeding-edge compiler flags.
WEE8_BUILD_ARGS+=" use_xcode_clang=true"
# Use local toolchain.
WEE8_BUILD_ARGS+=" custom_toolchain=\"//build/toolchain/linux/unbundle:default\""
# Use local stdlibc++ / libc++.
WEE8_BUILD_ARGS+=" use_custom_libcxx=false"
# Use local sysroot.
WEE8_BUILD_ARGS+=" use_sysroot=false"
# Disable unused GLib2 dependency.
WEE8_BUILD_ARGS+=" use_glib=false"
# Expose debug symbols.
WEE8_BUILD_ARGS+=" v8_expose_symbols=true"
# Build monolithic library.
WEE8_BUILD_ARGS+=" is_component_build=false"
WEE8_BUILD_ARGS+=" v8_enable_i18n_support=false"
WEE8_BUILD_ARGS+=" v8_enable_gdbjit=false"
WEE8_BUILD_ARGS+=" v8_use_external_startup_data=false"
# Disable read-only heap, since it'\''s leaky and HEAPCHECK complains about it.
# TODO(PiotrSikora): remove when fixed upstream.
WEE8_BUILD_ARGS+=" v8_enable_shared_ro_heap=false"
# Support Arm64
if [[ `uname -m` == "aarch64" ]]; then
  WEE8_BUILD_ARGS+=" target_cpu=\"arm64\""
fi

# Build wee8.
if [[ "$(uname -s)" == "Darwin" ]]; then
  gn=buildtools/mac/gn
  ninja=third_party/depot_tools/ninja
elif [[ "$(uname -s)-$(uname -m)" == "Linux-x86_64" ]]; then
  gn=buildtools/linux64/gn
  ninja=third_party/depot_tools/ninja
else
  # Using system default ninja & gn tools
  gn=$(command -v gn)
  ninja=$(command -v ninja)
fi
"$gn" gen out/wee8 --args="$WEE8_BUILD_ARGS"
"$ninja" -C out/wee8 wee8

# Move compiled library to the expected destinations.
popd
mv $ROOT/wee8/out/wee8/obj/libwee8.a bazel-out/aarch64-opt/bin/external/com_googlesource_chromium_v8/libwee8.a
')
/root/.cache/bazel/_bazel_root/596b0cd1ad0211ef049437fdd23e86ea/sandbox/processwrapper-sandbox/624/execroot/io_istio_proxy/external/com_googlesource_chromium_v8/wee8 /root/.cache/bazel/_bazel_root/596b0cd1ad0211ef049437fdd23e86ea/sandbox/processwrapper-sandbox/624/execroot/io_istio_proxy

**Comment by morlay** [comment]
google-gn version issue. i upgraded build-env.

`docker pull querycapistio/istio-envoy-arm64-build-env:0.0.0`
and run `make build` again.

**Comment by huanghuangzym** [comment]
> google-gn version issue. i upgraded build-env.
> 
> `docker pull querycapistio/istio-envoy-arm64-build-env:0.0.0`
> and run `make build` again.

[root@acp29-master-0001 istio-envoy-arm64]# docker images  --digests  |grep envoy
querycapistio/istio-envoy-arm64-build-env   0.0.0                                      sha256:3c92e3e5547507e18a104bd940a09eda791495ad97fae55306799a4a2e22a39a   4b8b5bb517c9        39 hours ago        2.87GB

is docker hub the latest ?
is this image fixed ?

**Comment by morlay** [comment]
is your host with `arm/v7`?

`arm/v7` is not support. 
64bit needed by google v8.

**Comment by huanghuangzym** [comment]
> is your host with `arm/v7`?
> 
> `arm/v7` is not support.
> 64bit needed by google v8.

[root@acp29-master-0001 istio-envoy-arm64]# uname -a
Linux acp29-master-0001 4.18.0-193.1.2.el7.aarch64 #1 SMP Fri May 29 18:22:47 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux

arm64 arch ,in huawei  kunpeng cpu

**Comment by morlay** [comment]
https://github.com/querycap/istio-envoy-arm64/runs/1165443486?check_suite_focus=true
the last build with that build-env-image.

which version of `docker` and `buildx`?

**Comment by huanghuangzym** [comment]
> https://github.com/querycap/istio-envoy-arm64/runs/1165443486?check_suite_focus=true
> the last build with that build-env-image.
> 
> which version of `docker` and `buildx`?

i find docker hub the latest is same with my pull image,the digests is same
[root@acp29-master-0001 istio-envoy-arm64]# docker version
Client: Docker Engine - Community
 Version:           18.09.9
 API version:       1.39
 Go version:        go1.11.13
 Git commit:        039a7df
 Built:             Wed Sep  4 16:50:24 2019
 OS/Arch:           linux/arm64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.9
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.13
  Git commit:       039a7df
  Built:            Wed Sep  4 16:55:08 2019
  OS/Arch:          linux/arm64
  Experimental:     true



i used docker build localy in arm ,  this is my modify   in makefile
VERSION=$(shell cat istio-envoy/Dockerfile.version | grep "^FROM " | sed -e "s/FROM.*://g" )
HUB=harbor.alauda.cn
TAG=devel
http_proxy=http://192.168.34.144:8118
https_proxy=http://192.168.34.144:8118


build:
        docker build \
                --build-arg VERSION=$(VERSION) \
                --build-arg HTTP_PROXY=$(http_proxy) \
                --build-arg HTTPS_PROXY=$(http_proxy) \
                --build-arg HTTP_PROXY=$(http_proxy) \
                --build-arg HTTPS_PROXY=$(http_proxy) \
                --tag $(HUB)/istio-envoy-arm64:$(VERSION) \
                -f istio-envoy/Dockerfile .

**Comment by morlay** [comment]
docker version may upgrade to 19.03

and could you check the build step?
```
Step 4/12 : RUN gn --version && bazel --version && ninja --version && clang++ --version
 ---> Running in af759ba32ab7
1781 (9a0496a7)
```

**Comment by huanghuangzym** [comment]
gn version is 1781 (9a0496a7)
ninja  version is 1.8.2

**Comment by morlay** [comment]
build-env image correctly.

added `RUN uname -a` after `WORKDIR /go/src` check the log?

**Comment by morlay** [comment]
upgrade docker version first.

if still not work. may need to edit `/etc/docker/daemon.json` and restart docker.
```
{
  "experimental": true
}
```

**Comment by huanghuangzym** [comment]
Step 1/13 : FROM querycapistio/istio-envoy-arm64-build-env:0.0.0 as builder
 ---> 4b8b5bb517c9
Step 2/13 : ARG VERSION=1.6.5
 ---> Using cache
 ---> 807b28259dc0
Step 3/13 : WORKDIR /go/src
 ---> Using cache
 ---> c20641cd262b
Step 4/13 : RUN uname -a
 ---> Running in 165efb1623d4
Linux 165efb1623d4 4.18.0-193.1.2.el7.aarch64 #1 SMP Fri May 29 18:22:47 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
Removing intermediate container 165efb1623d4
 ---> d08fa0bb1e1e

**Comment by huanghuangzym** [comment]
> upgrade docker version first.
> 
> if still not work. may need to edit `/etc/docker/daemon.json` and restart docker.
> 
> ```
> {
>   "experimental": true
> }
> ```

i   do not use buildx ,   i  build  it use "docker build"  in local arm linux mechine, 
is it must use docker buildx to build ?

**Comment by morlay** [comment]
nope. `docker build` could work. 
but my env with docker `19.03.x` any `Ubuntu 18.04`

docker old version may not support arm64. i haven't check it.

**Comment by huanghuangzym** [comment]
> nope. `docker build` could work.
> but my env with docker `19.03.x` any `Ubuntu 18.04`
> 
> docker old version may not support arm64. i haven't check it.

ok  , i  will update docker version   and docker buildx version ,and try it ,thanks
